zk:
  url: zookeeper://172.31.100.175:2182
  servers: 172.31.100.175:2182
  sessionTimeoutMs: 30000
  syncTimeMs: 5000
  connectionTimeoutMs: 5000
spring:
  redis:
    database: 1
    host: 172.31.100.164
    port: 6379
    password: QM0t2ZRyjQU3
    timeout: 3000
    pool:
      max-active: 50
      max-wait: 3000
      max-idle: 10
      min-idle: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/